@startuml
' scale 1800 width


[*] --> CreateNewGame
state CreateNewGame #gray {
    state SelectDifficulty {
        SetStartingAge -> SetFactions
        SetStartingAge: Early Age (hard)
        SetStartingAge: Middle Age (normal)
        SetStartingAge : Late Age (easy)

        SetFactions -> SetStartingLocation
        SetFactions : more enemies, less\n territory
        SetFactions : Calm
        SetFactions : Tense
        SetFactions : Hostile

        SetStartingLocation -> SetPatrons
        SetStartingLocation : Locales have different\n benefits and challenges

        SetPatrons -> SetStartingHeroProfessions
        SetPatrons : Game offers patrons at start
        SetPatrons : - Get unique bonuses
        SetPatrons : - Get access to funds
        SetPatrons : - Mandatory missions
        SetPatrons : - Will determine starting POG
        SetPatrons : (this is like gods in SQ)

        SetStartingHeroProfessions : Limited options
        SetStartingHeroProfessions : - Depends on locale
        SetStartingHeroProfessions : - Depends on factions
        SetStartingHeroProfessions : - Depends on starting age
        SetStartingHeroProfessions : - Depends on patrons
    }

    SelectDifficulty --> WorldCreation
    state WorldCreation {
        state GenerateWorld {
            SetWorldSize -> GenerateTerritories
            GenerateTerritories ->  SetLocation
        }

        GenerateWorld --> GenerateFactions
        state GenerateFactions {
            GenerateCitizens -> GenerateStartingRumors
            GenerateStartingRumors -> GenerateStartingQuests
        }

        GenerateFactions --> GenerateHeroes
        state GenerateHeroes {
            SetAttributes -> SetStartingEquipment
            SetStartingEquipment -> SetProfessionAbilities
        }
    }

    WorldCreation --> SpawnContractor
    state SpawnContractor {
        SetPartyFunds -> SetPartyHeroes
        SetPartyFunds : Influenced by patrons

        SetPartyHeroes -> SetPartySupplies
        SetPartySupplies : Basic wagon
        SetPartySupplies : Basic backpack
        SetPartySupplies : Poor quality tools

        SetPartySupplies -> SetContracts
        SetContracts : Quests
        SetContracts : Expedition orders
    }

    SpawnContractor --> SpawnChancellor
    state SpawnChancellor {
        SetCouncil -> SetTrade
    }

    SpawnChancellor --> SetInitialScene
    state SetInitialScene {
        state branch_SetInitialScene <<choice>>
        SetStartCamera --> branch_SetInitialScene
        branch_SetInitialScene --> SetExpeditionCamera : if on expedition
        branch_SetInitialScene --> SetFactionCamera : if not on expedition
    }

    SetInitialScene --> SpawnPlayerController
    state SpawnPlayerController {
        SetMouseListener -> SetKeyListener
        SetKeyListener -> ApplyCustomBindings
        ApplyCustomBindings -> MapBindingToFunction
    }
}

CreateNewGame --> GameLoop : Player is given\n control and taken\n to the game


state GameLoop {
    ' START Definitions

    state ResourceSystem {
        state ResourceStock
        state MaterialResource
        state FieldResource

        ResourceProducingBuilding --> ResourceStock : Generate resources

        ResourceStock --> Industry : Consumed by

        MaterialResource -> FieldCrafting
        FieldResource --> FieldCrafting

        MaterialResource --> FactionCrafting
        ResourceStock --> FactionCrafting
    }

    state Chancellor {
        state Industry
        state Diplomacy {
            state Council
            state Treasury
            state Policies
            state Population
            state Trade
        }
    }

    state Contractor {
        state ViewJobBoard
        state AcceptJob
        state PartyFunds

        state GuildmasterSystem {
            state CraftQuest {
                state CollectQuestComponents
            }
            state EstablishmentManagement
        }

        state ExpeditionSystem {
            state CreateContract
        }
    }

    state Crafting {
        Crafting : Can be done any time player is off expedition

        state FactionCrafting {

        }

        state FieldCrafting {

        }
    }


    ' END Definitions

    state Chancellor {
        state ManageTerritory {
            state CreateBuildingHere {
                SelectResource --> SelectBuilding
                SelectBuilding --> PayBuildingFees
                PayBuildingFees --> WaitForSomeTime
                WaitForSomeTime --> BuildingComplete
                BuildingComplete --> ResourceProducingBuilding
            }

            CreateTradeRouteHere -> Trade
            CreateTradeRouteHere : If clicking on territory owned by\n allied faction

            state BuildRoadHere {
                SelectRoadType --> PayRoadBuildingFees
                PayRoadBuildingFees --> WaitForSomeTimeForRoad
                WaitForSomeTimeForRoad --> ImprovesTravelSpeedHere
            }

            CreateExpeditionHere --> CreateContract
        }

        state Industry {
            SelectIndustryType --> SelectResourceBuildings
            SelectIndustryType : - Steel, paper, stream gel

            SelectResourceBuildings : - Selected buildings will ONLY\n send goods here
            SelectResourceBuildings : - Other industries may be needed

            SelectResourceBuildings --> ConnectToResourceBuildings
            ConnectToResourceBuildings : - Make sure a road exists\n and you own the territory
        }
    }

    state Contractor {
        ViewJobBoard --> AcceptJob
        AcceptJob -> CreateContract

        state PartyManagementSystem {
            EnterNewTerritory -> AtAnyPoint

            state EnterNewTerritory {
                GenerateEnvironment --> GenerateResources
                GenerateResources --> GenerateRandomEvents
                GenerateRandomEvents --> GenerateEnemies
            }

            RandomEvents --> Highwaypersons
            RandomEvents --> SideJobs
            RandomEvents --> StrandedVillager
            RandomEvents --> Villages
            RandomEvents --> StreamPortals
            RandomEvents --> Junkyards

            Villages --> EstablishOutpost
            Villages --> RaidVillages

            Villages : - Kind of like above-ground dungeons
            Villages : - Abandoned. May contain squatters
            Villages : - More devices, blueprints, lore
            Villages : - Can claim as an outpost
            StreamPortals : - Open portals for stream gel
            StreamPortals : - Fight monsters
            StreamPortals : - Close portals for stream gel\n after all monsters gone
            Junkyards : - Chance to spawn in certain territories
            Junkyards : - Increased chance of devices
            Junkyards : - More bizzarre/difficult monsters

            AtAnyPoint --> Combat
            AtAnyPoint -> RandomEvents
            AtAnyPoint --> GatherResources
            AtAnyPoint --> ReturnToWagon

            RaidVillages --> GatherLoot
            RaidVillages --> Combat

            Highwaypersons --> Combat
            StreamPortals --> Combat

            SideJobs --> Combat

            Junkyards --> StreamPortals
            Junkyards --> Combat

            state HarvestCreature
            state GatherLoot
            state ReturnToWagon

            state Combat {
                state PreEngagement {
                    state SetUpTrap
                    state DrinkPotion
                    state ApplyWeaponOils
                }

                state CombatLoop {
                    state CreatureAttacks {
                        state AttackWithWeapon
                        state PerformAbility
                        state UseCombatItem {
                            state ThrowBomb
                        }
                    }

                    ApplyEnvironmentalEffects --> CreatureAttacks
                    CreatureAttacks : - Fire damage from terrain, Poison clouds
                    CreatureAttacks : - Rain, Snow, Ice
                    CreatureAttacks --> CreatureDefenses
                    CreatureDefenses : Damage is passed through defenses

                    state CreatureDefenses {
                        state PhysicalDefense {
                            state Evasion
                            state PiercingDefense
                            state CrushingDefense
                            state SlashingDefense
                        }
                        state MagicalDefense {
                            state FireDefense
                            state WaterDefense
                            state ToxinDefense
                        }
                    }

                    CreatureDefenses --> AdjustCreatureStats : Take damage, apply temporary effects, etc.
                    AdjustCreatureStats --> IsCreatureDead

                    state cc <<choice>>
                    IsCreatureDead --> cc
                    cc --> CombatEnded : yes
                    cc -> NewCombatTurn : no
                    NewCombatTurn --> Flee
                    NewCombatTurn --> ApplyEnvironmentalEffects
                }

                PreEngagement --> NewCombatTurn : Engage creature

                CombatEnded --> HarvestCreature
                CombatEnded --> GatherLoot

                HarvestCreature --> GatherLoot
                GatherLoot --> ReturnToWagon
            }


            GatherResources --> MaterialResource
            GatherResources --> FieldResource
            GatherResources --> ReturnToWagon

            ReturnToWagon --> FieldCrafting
            ReturnToWagon --> Rest
            state Rest {
                state BuildCamp
                state RestAtInn

                RestAtInn --> GainRestedBonus
                GainRestedBonus --> RecoverHealth

                BuildCamp --> Ambushed
                BuildCamp --> RecoverHealth

                Ambushed --> ReturnToWagon
                RecoverHealth --> ReturnToWagon
            }
            ReturnToWagon --> EnterNewTerritory
        }

        state ExpeditionSystem {
            FromPatron --> CreateContract : AcceptGrant

            CreateContract --> PrepareStage
            CreateContract : Tells you how long you have to complete\n measured in days of rest
            CreateContract : So you should buy enough food to rest

            state PrepareStage {
                state HireHeroes {
                    ViewHeroMap -> SelectHeroes
                    SelectHeroes -> SetMeetingPoint
                    SetMeetingPoint : The territory that the expedition will depart from
                    SetMeetingPoint : Everyone will meet each other here
                }
                state HireWagonGuard
                HireWagonGuard : More canary than guard

                state PurchaseConsumables
                PurchaseConsumables : - Food (affects expedition duration)
                PurchaseConsumables : - Elixirs

                state SendScout
                SendScout : - Costs money per distance\n  and difficulty
                SendScout : - % of success per Scout level
                SendScout : - Shows threats and POI

                state AddStreamCollector
                AddStreamCollector : Increases rewards and threat
            }

            PrepareStage --> AdventureStage : Embark
            state AdventureStage {

            }

            AdventureStage --> EnterNewTerritory : Moving between territories
            EnterNewTerritory --> AdventureStage

            AdventureStage --> RescueStage : FailedContract
            AdventureStage --> RewardStage : SuccessfulContract

            state RewardStage {
                DepositRewardFunds --> DepositItemRewards
                DepositRewardFunds --> PartyFunds
                DepositItemRewards --> SellFieldResourcesForCurrency
                SellFieldResourcesForCurrency --> PartyFunds
                SellFieldResourcesForCurrency --> VisitExtractors
                VisitExtractors --> SellLootToCollectors
                SellLootToCollectors --> PartyFunds
            }
        }
    }

    state GuildmasterSystem {
        state CraftQuest {

            CollectQuestComponents --> DepositFunds
            DepositFunds --> PostInGuild
            PostInGuild --> GuildmembersAccept
            GuildmembersAccept --> RunExpedition
            RunExpedition --> PlayerReceivesRewards
            PlayerReceivesRewards --> PlayerRunsExpedition
            PlayerRunsExpedition --> CollectQuestComponents
        }

        state EstablishmentManagement {
            ImproveGuildHall --> AttractBetterHeroes
            AttractBetterHeroes --> MoreChallengingQuests
            MoreChallengingQuests --> MoreProfit
            MoreProfit --> ImproveGuildHall
        }
    }
}

@enduml